# Scheme name: Tokyodark Terminal
# Scheme author: Tiagovla (https://github.com/tiagovla/)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Tokyodark Terminal.16
ColorForeground=#a0a8cd
ColorBackground=#11121d
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#1a1b2a;#ee6d85;#95c561;#d7a65f;#7199ee;#773440;#38a89d;#a0a8cd;#11121d;#f6955b;#212234;#282c34;#4a5057;#a485dd;#a0a8cd;#a0a8cd
