# Scheme name: Horizon Dark
# Scheme author: Michaël Ball (http://github.com/michael-ball/)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Horizon Dark
ColorForeground=#cbced0
ColorBackground=#1c1e26
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#1c1e26;#e93c58;#efaf8e;#efb993;#df5273;#b072d1;#24a8b4;#cbced0;#6f6f70;#e93c58;#efaf8e;#efb993;#df5273;#b072d1;#24a8b4;#e3e6ee
