# Scheme name: Brush Trees Dark
# Scheme author: Abraham White &lt;abelincoln.white@gmail.com&gt;
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Brush Trees Dark.16
ColorForeground=#b0c5c8
ColorBackground=#485867
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#5a6d7a;#b38686;#87b386;#aab386;#868cb3;#b39f9f;#86b3b3;#c9dbdc;#485867;#d8bba2;#6d828e;#8299a1;#98afb5;#b386b2;#b0c5c8;#e3efef
