# Scheme name: Everforest
# Scheme author: Sainnhe Park (https://github.com/sainnhe)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Everforest
ColorForeground=#d3c6aa
ColorBackground=#2d353b
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#2d353b;#e67e80;#a7c080;#dbbc7f;#7fbbb3;#d699b6;#83c092;#d3c6aa;#859289;#e67e80;#a7c080;#dbbc7f;#7fbbb3;#d699b6;#83c092;#fdf6e3
