# Scheme name: Tomorrow Night Eighties
# Scheme author: Chris Kempson (http://chriskempson.com)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Tomorrow Night Eighties.16
ColorForeground=#cccccc
ColorBackground=#2d2d2d
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#393939;#f2777a;#99cc99;#ffcc66;#6699cc;#a3685a;#66cccc;#e0e0e0;#2d2d2d;#f99157;#515151;#999999;#b4b7b4;#cc99cc;#cccccc;#ffffff
