# Scheme name: Precious Dark Fifteen
# Scheme author: 4lex4 &lt;4lex49@zoho.com&gt;
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Precious Dark Fifteen.16
ColorForeground=#bab9b6
ColorBackground=#23262b
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#303337;#ff8782;#95b659;#cfa546;#66b0ef;#f382d8;#42bda7;#bab9b6;#23262b;#e99857;#3e4044;#898989;#abaaa8;#b799ff;#bab9b6;#bab9b6
