# Scheme name: Ayu Mirage
# Scheme author: Khue Nguyen &lt;Z5483Y@gmail.com&gt;
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Ayu Mirage
ColorForeground=#cccac2
ColorBackground=#171b24
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#171b24;#f28779;#d5ff80;#ffd173;#5ccfe6;#d4bfff;#95e6cb;#cccac2;#707a8c;#f28779;#d5ff80;#ffd173;#5ccfe6;#d4bfff;#95e6cb;#f3f4f5
