# Scheme name: Atelier Cave
# Scheme author: Bram de Haan (http://atelierbramdehaan.nl)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Atelier Cave
ColorForeground=#8b8792
ColorBackground=#19171c
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#19171c;#be4678;#2a9292;#a06e3b;#576ddb;#955ae7;#398bc6;#8b8792;#655f6d;#be4678;#2a9292;#a06e3b;#576ddb;#955ae7;#398bc6;#efecf4
