# Scheme name: Atelier Lakeside Light
# Scheme author: Bram de Haan (http://atelierbramdehaan.nl)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-atelier-lakeside-light
ColorForeground=#516d7b
ColorBackground=#ebf8ff
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#ebf8ff;#d22d72;#568c3b;#8a8a0f;#257fad;#6b6bb8;#2d8f6f;#516d7b;#7ea2b4;#d22d72;#568c3b;#8a8a0f;#257fad;#6b6bb8;#2d8f6f;#161b1d
