# Scheme name: Black Metal (Marduk)
# Scheme author: metalelf0 (https://github.com/metalelf0)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Black Metal (Marduk)
ColorForeground=#c1c1c1
ColorBackground=#000000
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#000000;#5f8787;#a5aaa7;#626b67;#888888;#999999;#aaaaaa;#c1c1c1;#333333;#5f8787;#a5aaa7;#626b67;#888888;#999999;#aaaaaa;#c1c1c1
