# Scheme name: Tokyo Night Terminal Light
# Scheme author: Michaël Ball
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Tokyo Night Terminal Light.16
ColorForeground=#4c505e
ColorBackground=#d5d6db
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#cbccd1;#8c4351;#33635c;#8f5e15;#34548a;#655259;#0f4b6e;#1a1b26;#d5d6db;#965027;#dfe0e5;#9699a3;#4c505e;#5a4a78;#4c505e;#1a1b26
