# Scheme name: selenized-light
# Scheme author: Jan Warchol (https://github.com/jan-warchol/selenized) / adapted to base16 by ali
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-selenized-light.16
ColorForeground=#53676d
ColorBackground=#fbf3db
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#ece3cc;#cc1729;#428b00;#a78300;#006dce;#c44392;#00978a;#3a4d53;#fbf3db;#bc5819;#d5cdb6;#909995;#909995;#825dc0;#53676d;#3a4d53
