# Scheme name: Rosé Pine Moon
# Scheme author: Emilia Dunfelt &lt;edun@dunfelt.se&gt;
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Rosé Pine Moon
ColorForeground=#e0def4
ColorBackground=#232136
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#232136;#eb6f92;#3e8fb0;#ea9a97;#c4a7e7;#f6c177;#9ccfd8;#e0def4;#6e6a86;#eb6f92;#3e8fb0;#ea9a97;#c4a7e7;#f6c177;#9ccfd8;#56526e
