# Scheme name: Dark Violet
# Scheme author: ruler501 (https://github.com/ruler501/base16-darkviolet)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Dark Violet.16
ColorForeground=#b08ae6
ColorBackground=#000000
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#231a40;#a82ee6;#4595e6;#f29df2;#4136d9;#a886bf;#40dfff;#9045e6;#000000;#bb66cc;#432d59;#593380;#00ff00;#7e5ce6;#b08ae6;#a366ff
