# Scheme name: Terracotta
# Scheme author: Alexander Rossell Hayes (https://github.com/rossellhayes)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Terracotta
ColorForeground=#473731
ColorBackground=#efeae8
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#efeae8;#a75045;#7a894a;#ce943e;#625574;#8d5968;#847f9e;#473731;#c0aca4;#a75045;#7a894a;#ce943e;#625574;#8d5968;#847f9e;#241c19
