# Scheme name: Google Dark
# Scheme author: Seth Wright (http://sethawright.com)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Google Dark
ColorForeground=#c5c8c6
ColorBackground=#1d1f21
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#1d1f21;#cc342b;#198844;#fba922;#3971ed;#a36ac7;#3971ed;#c5c8c6;#969896;#cc342b;#198844;#fba922;#3971ed;#a36ac7;#3971ed;#ffffff
