# Scheme name: Atelier Sulphurpool
# Scheme author: Bram de Haan (http://atelierbramdehaan.nl)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Atelier Sulphurpool.16
ColorForeground=#979db4
ColorBackground=#202746
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#293256;#c94922;#ac9739;#c08b30;#3d8fd1;#9c637a;#22a2c9;#dfe2f1;#202746;#c76b29;#5e6687;#6b7394;#898ea4;#6679cc;#979db4;#f5f7ff
