# Scheme name: XCode Dusk
# Scheme author: Elsa Gonsiorowski (https://github.com/gonsie)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-XCode Dusk
ColorForeground=#939599
ColorBackground=#282b35
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#282b35;#b21889;#df0002;#438288;#790ead;#b21889;#00a0be;#939599;#686a71;#b21889;#df0002;#438288;#790ead;#b21889;#00a0be;#bebfc2
