# Scheme name: Rosé Pine
# Scheme author: Emilia Dunfelt &lt;sayhi@dunfelt.se&gt;
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Rosé Pine
ColorForeground=#e0def4
ColorBackground=#191724
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#191724;#e2e1e7;#ebbcba;#f6c177;#9ccfd8;#c4a7e7;#31748f;#e0def4;#555169;#e2e1e7;#ebbcba;#f6c177;#9ccfd8;#c4a7e7;#31748f;#c5c3ce
