# Scheme name: PhD
# Scheme author: Hennig Hasemann (http://leetless.de/vim.html)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-PhD.16
ColorForeground=#b8bbc2
ColorBackground=#061229
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#2a3448;#d07346;#99bf52;#fbd461;#5299bf;#b08060;#72b9bf;#dbdde0;#061229;#f0a000;#4d5666;#717885;#9a99a3;#9989cc;#b8bbc2;#ffffff
