# Scheme name: Edge Dark
# Scheme author: cjayross (https://github.com/cjayross)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-edge-dark
ColorForeground=#b7bec9
ColorBackground=#262729
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#262729;#e77171;#a1bf78;#dbb774;#73b3e7;#d390e7;#5ebaa5;#b7bec9;#b7bec9;#e77171;#a1bf78;#dbb774;#73b3e7;#d390e7;#5ebaa5;#3e4249
