# Scheme name: One Light
# Scheme author: Daniel Pfeifer (http://github.com/purpleKarrot)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-One Light.16
ColorForeground=#383a42
ColorBackground=#fafafa
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#f0f0f1;#ca1243;#50a14f;#c18401;#4078f2;#986801;#0184bc;#202227;#fafafa;#d75f00;#e5e5e6;#a0a1a7;#696c77;#a626a4;#383a42;#090a0b
