# Scheme name: XCode Dusk
# Scheme author: Elsa Gonsiorowski (https://github.com/gonsie)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-XCode Dusk.16
ColorForeground=#939599
ColorBackground=#282b35
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#3d4048;#b21889;#df0002;#438288;#790ead;#c77c48;#00a0be;#a9aaae;#282b35;#786dc5;#53555d;#686a71;#7e8086;#b21889;#939599;#bebfc2
