# Scheme name: Blue Forest
# Scheme author: alonsodomin (https://github.com/alonsodomin)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Blue Forest
ColorForeground=#ffcc33
ColorBackground=#141f2e
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#141f2e;#fffab1;#80ff80;#91ccff;#a2cff5;#0099ff;#80ff80;#ffcc33;#a0ffa0;#fffab1;#80ff80;#91ccff;#a2cff5;#0099ff;#80ff80;#375780
