# Scheme name: Precious Dark Fifteen
# Scheme author: 4lex4 &lt;4lex49@zoho.com&gt;
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Precious Dark Fifteen
ColorForeground=#bab9b6
ColorBackground=#23262b
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#23262b;#ff8782;#95b659;#cfa546;#66b0ef;#b799ff;#42bda7;#bab9b6;#898989;#ff8782;#95b659;#cfa546;#66b0ef;#b799ff;#42bda7;#bab9b6
