# Scheme name: Porple
# Scheme author: Niek den Breeje (https://github.com/AuditeMarlow)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Porple.16
ColorForeground=#d8d8d8
ColorBackground=#292c36
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#333344;#f84547;#95c76f;#efa16b;#8485ce;#986841;#64878f;#e8e8e8;#292c36;#d28e5d;#474160;#65568a;#b8b8b8;#b74989;#d8d8d8;#f8f8f8
