# Scheme name: Atelier Estuary Light
# Scheme author: Bram de Haan (http://atelierbramdehaan.nl)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Atelier Estuary Light.16
ColorForeground=#5f5e4e
ColorBackground=#f4f3ec
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#e7e6df;#ba6236;#7d9726;#a5980d;#36a166;#9d6c7c;#5b9d48;#302f27;#f4f3ec;#ae7313;#929181;#878573;#6c6b5a;#5f9182;#5f5e4e;#22221b
