# Scheme name: Unikitty Reversible
# Scheme author: Josh W Lewis (@joshwlewis)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Unikitty Reversible
ColorForeground=#c3c2c4
ColorBackground=#2e2a31
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#2e2a31;#d8137f;#17ad98;#dc8a0e;#7864fa;#b33ce8;#149bda;#c3c2c4;#878589;#d8137f;#17ad98;#dc8a0e;#7864fa;#b33ce8;#149bda;#ffffff
