# Scheme name: Atelier Plateau
# Scheme author: Bram de Haan (http://atelierbramdehaan.nl)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Atelier Plateau.16
ColorForeground=#8a8585
ColorBackground=#1b1818
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#292424;#ca4949;#4b8b8b;#a06e3b;#7272ca;#bd5187;#5485b6;#e7dfdf;#1b1818;#b45a3c;#585050;#655d5d;#7e7777;#8464c4;#8a8585;#f4ecec
