# Scheme name: Apathy
# Scheme author: Jannik Siebert (https://github.com/janniks)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Apathy
ColorForeground=#81b5ac
ColorBackground=#031a16
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#031a16;#3e9688;#883e96;#3e4c96;#96883e;#4c963e;#963e4c;#81b5ac;#2b685e;#3e9688;#883e96;#3e4c96;#96883e;#4c963e;#963e4c;#d2e7e4
