# Scheme name: Bright
# Scheme author: Chris Kempson (http://chriskempson.com)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Bright.16
ColorForeground=#e0e0e0
ColorBackground=#000000
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#303030;#fb0120;#a1c659;#fda331;#6fb3d2;#be643c;#76c7b7;#f5f5f5;#000000;#fc6d24;#505050;#b0b0b0;#d0d0d0;#d381c3;#e0e0e0;#ffffff
