# Scheme name: Solarized Light
# Scheme author: Ethan Schoonover (modified by aramisgithub)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Solarized Light.16
ColorForeground=#586e75
ColorBackground=#fdf6e3
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#eee8d5;#dc322f;#859900;#b58900;#268bd2;#d33682;#2aa198;#073642;#fdf6e3;#cb4b16;#93a1a1;#839496;#657b83;#6c71c4;#586e75;#002b36
