# Scheme name: DanQing Light
# Scheme author: Wenhan Zhu (Cosmos) (zhuwenhan950913@gmail.com)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-DanQing Light
ColorForeground=#5a605d
ColorBackground=#fcfefd
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#fcfefd;#f9906f;#8ab361;#f0c239;#b0a4e3;#cca4e3;#30dff3;#5a605d;#cad8d2;#f9906f;#8ab361;#f0c239;#b0a4e3;#cca4e3;#30dff3;#2d302f
