# Scheme name: Black Metal (Venom)
# Scheme author: metalelf0 (https://github.com/metalelf0)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Black Metal (Venom)
ColorForeground=#c1c1c1
ColorBackground=#000000
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#000000;#5f8787;#f8f7f2;#79241f;#888888;#999999;#aaaaaa;#c1c1c1;#333333;#5f8787;#f8f7f2;#79241f;#888888;#999999;#aaaaaa;#c1c1c1
