# Scheme name: DanQing
# Scheme author: Wenhan Zhu (Cosmos) (zhuwenhan950913@gmail.com)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-DanQing
ColorForeground=#e0f0ef
ColorBackground=#2d302f
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#2d302f;#f9906f;#8ab361;#f0c239;#b0a4e3;#cca4e3;#30dff3;#e0f0ef;#9da8a3;#f9906f;#8ab361;#f0c239;#b0a4e3;#cca4e3;#30dff3;#fcfefd
