# Scheme name: Everforest
# Scheme author: Sainnhe Park (https://github.com/sainnhe)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Everforest
ColorForeground=#d3c6aa
ColorBackground=#2f383e
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#2f383e;#7fbbb3;#83c092;#dbbc7f;#a7c080;#e67e80;#e69875;#d3c6aa;#859289;#7fbbb3;#83c092;#dbbc7f;#a7c080;#e67e80;#e69875;#fdf6e3
