# Scheme name: Da One Paper
# Scheme author: NNB (https://github.com/NNBnh)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Da One Paper
ColorForeground=#181818
ColorBackground=#faf0dc
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#faf0dc;#de5d6e;#76a85d;#b3684f;#5890f8;#c173d1;#64b5a7;#181818;#585858;#de5d6e;#76a85d;#b3684f;#5890f8;#c173d1;#64b5a7;#000000
