# Scheme name: Gruvbox Material Light, Hard
# Scheme author: Mayush Kumar (https://github.com/MayushKumar), sainnhe (https://github.com/sainnhe/gruvbox-material-vscode)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Gruvbox Material Light, Hard
ColorForeground=#654735
ColorBackground=#f9f5d7
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#f9f5d7;#c14a4a;#6c782e;#b47109;#45707a;#945e80;#4c7a5d;#654735;#a89984;#c14a4a;#6c782e;#b47109;#45707a;#945e80;#4c7a5d;#282828
