# Scheme name: Silk Dark
# Scheme author: Gabriel Fontes (https://github.com/Misterio77)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Silk Dark.16
ColorForeground=#c7dbdd
ColorBackground=#0e3c46
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#1d494e;#fb6953;#73d8ad;#fce380;#46bddd;#9b647b;#3fb2b9;#cbf2f7;#0e3c46;#fcab74;#2a5054;#587073;#9dc8cd;#756b8a;#c7dbdd;#d2faff
