# Scheme name: Rebecca
# Scheme author: Victor Borja (http://github.com/vic) based on Rebecca Theme (http://github.com/vic/rebecca-theme)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Rebecca
ColorForeground=#f1eff8
ColorBackground=#292a44
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#292a44;#a0a0c5;#6dfedf;#ae81ff;#2de0a7;#7aa5ff;#8eaee0;#f1eff8;#666699;#a0a0c5;#6dfedf;#ae81ff;#2de0a7;#7aa5ff;#8eaee0;#53495d
