# Scheme name: Rosé Pine
# Scheme author: Emilia Dunfelt &lt;edun@dunfelt.se&gt;
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Rosé Pine
ColorForeground=#e0def4
ColorBackground=#191724
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#191724;#eb6f92;#31748f;#ebbcba;#c4a7e7;#f6c177;#9ccfd8;#e0def4;#6e6a86;#eb6f92;#31748f;#ebbcba;#c4a7e7;#f6c177;#9ccfd8;#524f67
