# Scheme name: DanQing Light
# Scheme author: Wenhan Zhu (Cosmos) (zhuwenhan950913@gmail.com)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-DanQing Light.16
ColorForeground=#5a605d
ColorBackground=#fcfefd
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#ecf6f2;#f9906f;#8ab361;#f0c239;#b0a4e3;#ca6924;#30dff3;#434846;#fcfefd;#b38a61;#e0f0ef;#cad8d2;#9da8a3;#cca4e3;#5a605d;#2d302f
