# Scheme name: Everforest
# Scheme author: Sainnhe Park (https://github.com/sainnhe)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Everforest.16
ColorForeground=#d3c6aa
ColorBackground=#2d353b
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#343f44;#e67e80;#a7c080;#dbbc7f;#7fbbb3;#9da9a0;#83c092;#e6e2cc;#2d353b;#e69875;#475258;#859289;#9da9a0;#d699b6;#d3c6aa;#fdf6e3
