# Scheme name: Ayu Dark
# Scheme author: Khue Nguyen &lt;Z5483Y@gmail.com&gt;
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-ayu-dark
ColorForeground=#e6e1cf
ColorBackground=#0f1419
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#0f1419;#f07178;#b8cc52;#ffb454;#59c2ff;#d2a6ff;#95e6cb;#e6e1cf;#272d38;#f07178;#b8cc52;#ffb454;#59c2ff;#d2a6ff;#95e6cb;#f3f4f5
