# Scheme name: Black Metal (Dark Funeral)
# Scheme author: metalelf0 (https://github.com/metalelf0)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Black Metal (Dark Funeral)
ColorForeground=#c1c1c1
ColorBackground=#000000
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#000000;#5f8787;#d0dfee;#5f81a5;#888888;#999999;#aaaaaa;#c1c1c1;#333333;#5f8787;#d0dfee;#5f81a5;#888888;#999999;#aaaaaa;#c1c1c1
