# Scheme name: Catppuccin Macchiato
# Scheme author: https://github.com/catppuccin/catppuccin
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Catppuccin Macchiato.16
ColorForeground=#cad3f5
ColorBackground=#24273a
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#1e2030;#ed8796;#a6da95;#eed49f;#8aadf4;#f0c6c6;#8bd5ca;#f4dbd6;#24273a;#f5a97f;#363a4f;#494d64;#5b6078;#c6a0f6;#cad3f5;#b7bdf8
