# Scheme name: Embers Light
# Scheme author: Jannik Siebert (https://github.com/janniks)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Embers Light.16
ColorForeground=#323b43
ColorBackground=#d1d6db
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#aeb6be;#576d82;#6d8257;#57826d;#82576d;#575782;#826d57;#20262c;#d1d6db;#578282;#909aa3;#75808a;#47505a;#6d5782;#323b43;#0f1316
