# Scheme name: Precious Light White
# Scheme author: 4lex4 &lt;4lex49@zoho.com&gt;
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Precious Light White
ColorForeground=#555555
ColorBackground=#ffffff
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#ffffff;#af4947;#557301;#876500;#186daa;#7b4ecb;#087767;#555555;#848484;#af4947;#557301;#876500;#186daa;#7b4ecb;#087767;#555555
