# Scheme name: Atelier Heath Light
# Scheme author: Bram de Haan (http://atelierbramdehaan.nl)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Atelier Heath Light.16
ColorForeground=#695d69
ColorBackground=#f7f3f7
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#d8cad8;#ca402b;#918b3b;#bb8a35;#516aec;#cc33cc;#159393;#292329;#f7f3f7;#a65926;#ab9bab;#9e8f9e;#776977;#7b59c0;#695d69;#1b181b
