# Scheme name: Rosé Pine Moon
# Scheme author: Emilia Dunfelt &lt;edun@dunfelt.se&gt;
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Rosé Pine Moon.16
ColorForeground=#e0def4
ColorBackground=#232136
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#2a273f;#eb6f92;#3e8fb0;#ea9a97;#c4a7e7;#56526e;#9ccfd8;#e0def4;#232136;#f6c177;#393552;#6e6a86;#908caa;#f6c177;#e0def4;#56526e
