# Scheme name: Windows NT
# Scheme author: Fergus Collins (https://github.com/C-Fergus)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-windows-nt
ColorForeground=#c0c0c0
ColorBackground=#000000
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#000000;#ff0000;#00ff00;#ffff00;#0000ff;#ff00ff;#00ffff;#c0c0c0;#555555;#ff0000;#00ff00;#ffff00;#0000ff;#ff00ff;#00ffff;#ffffff
