# Scheme name: Tokyo City Light
# Scheme author: Michaël Ball
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Tokyo City Light.16
ColorForeground=#343b59
ColorBackground=#fbfbfd
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#f6f6f8;#8c4351;#485e30;#4c505e;#34548a;#5a4a78;#4c505e;#1d252c;#fbfbfd;#965027;#edeff6;#9699a3;#4c505e;#5a4a78;#343b59;#171d23
