# Scheme name: Brush Trees
# Scheme author: Abraham White &lt;abelincoln.white@gmail.com&gt;
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Brush Trees
ColorForeground=#6d828e
ColorBackground=#e3efef
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#e3efef;#b38686;#87b386;#aab386;#868cb3;#b386b2;#86b3b3;#6d828e;#98afb5;#b38686;#87b386;#aab386;#868cb3;#b386b2;#86b3b3;#485867
