# Scheme name: summercamp
# Scheme author: zoe firi (zoefiri.github.io)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-summercamp.16
ColorForeground=#736e55
ColorBackground=#1c1810
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#2a261c;#e35142;#5ceb5a;#f2ff27;#489bf0;#f69be7;#5aebbc;#bab696;#1c1810;#fba11b;#3a3527;#504b38;#5f5b45;#ff8080;#736e55;#f8f5de
