# Scheme name: Windows High Contrast Light
# Scheme author: Fergus Collins (https://github.com/C-Fergus)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Windows High Contrast Light.16
ColorForeground=#545454
ColorBackground=#fcfcfc
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#e8e8e8;#800000;#008000;#808000;#000080;#54fc54;#008080;#2a2a2a;#fcfcfc;#fcfc54;#d4d4d4;#c0c0c0;#7e7e7e;#800080;#545454;#000000
