# Scheme name: Solar Flare
# Scheme author: Chuck Harmston (https://chuck.harmston.ch)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Solar Flare.16
ColorForeground=#a6afb8
ColorBackground=#18262f
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#222e38;#ef5253;#7cc844;#e4b51c;#33b5e1;#d73c9a;#52cbb0;#e8e9ed;#18262f;#e66b2b;#586875;#667581;#85939e;#a363d5;#a6afb8;#f5f7fa
