# Scheme name: 3024
# Scheme author: Jan T. Sott (http://github.com/idleberg)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-3024.16
ColorForeground=#a5a2a2
ColorBackground=#090300
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#3a3432;#db2d20;#01a252;#fded02;#01a0e4;#cdab53;#b5e4f4;#d6d5d4;#090300;#e8bbd0;#4a4543;#5c5855;#807d7c;#a16a94;#a5a2a2;#f7f7f7
