# Scheme name: Da One White
# Scheme author: NNB (https://github.com/NNBnh)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Da One White
ColorForeground=#181818
ColorBackground=#ffffff
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#ffffff;#de5d6e;#76a85d;#b3684f;#5890f8;#c173d1;#64b5a7;#181818;#585858;#de5d6e;#76a85d;#b3684f;#5890f8;#c173d1;#64b5a7;#000000
