# Scheme name: Windows High Contrast
# Scheme author: Fergus Collins (https://github.com/C-Fergus)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Windows High Contrast.16
ColorForeground=#c0c0c0
ColorBackground=#000000
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#1c1c1c;#fc5454;#54fc54;#fcfc54;#5454fc;#008000;#54fcfc;#dedede;#000000;#808000;#383838;#545454;#a2a2a2;#fc54fc;#c0c0c0;#fcfcfc
