# Scheme name: Colors
# Scheme author: mrmrs (http://clrs.cc)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-colors
ColorForeground=#bbbbbb
ColorBackground=#111111
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#111111;#ff4136;#2ecc40;#ffdc00;#0074d9;#b10dc9;#7fdbff;#bbbbbb;#555555;#ff4136;#2ecc40;#ffdc00;#0074d9;#b10dc9;#7fdbff;#ffffff
