# Scheme name: Atelier Seaside Light
# Scheme author: Bram de Haan (http://atelierbramdehaan.nl)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Atelier Seaside Light.16
ColorForeground=#5e6e5e
ColorBackground=#f4fbf4
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#cfe8cf;#e6193c;#29a329;#98981b;#3d62f5;#e619c3;#1999b3;#242924;#f4fbf4;#87711d;#8ca68c;#809980;#687d68;#ad2bee;#5e6e5e;#131513
