# Scheme name: Heetch Light
# Scheme author: Geoffrey Teale (tealeg@gmail.com)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Heetch Light.16
ColorForeground=#5a496e
ColorBackground=#feffff
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#392551;#27d9d5;#f80059;#5ba2b6;#47f9f5;#dedae2;#c33678;#470546;#feffff;#bdb6c5;#7b6d8b;#9c92a8;#ddd6e5;#bd0152;#5a496e;#190134
