# Scheme name: Summerfruit Light
# Scheme author: Christopher Corley (http://christop.club/)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Summerfruit Light
ColorForeground=#101010
ColorBackground=#ffffff
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#ffffff;#ff0086;#00c918;#aba800;#3777e6;#ad00a1;#1faaaa;#101010;#b0b0b0;#ff0086;#00c918;#aba800;#3777e6;#ad00a1;#1faaaa;#202020
