# Scheme name: Google Light
# Scheme author: Seth Wright (http://sethawright.com)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Google Light.16
ColorForeground=#373b41
ColorBackground=#ffffff
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#e0e0e0;#cc342b;#198844;#fba922;#3971ed;#3971ed;#3971ed;#282a2e;#ffffff;#f96a38;#c5c8c6;#b4b7b4;#969896;#a36ac7;#373b41;#1d1f21
