# Scheme name: Everforest
# Scheme author: Sainnhe Park (https://github.com/sainnhe)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Everforest.16
ColorForeground=#d3c6aa
ColorBackground=#2f383e
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#374247;#7fbbb3;#83c092;#dbbc7f;#a7c080;#eaedc8;#e69875;#e4e1cd;#2f383e;#d699b6;#4a555b;#859289;#9da9a0;#e67e80;#d3c6aa;#fdf6e3
