# Scheme name: Windows High Contrast Light
# Scheme author: Fergus Collins (https://github.com/C-Fergus)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Windows High Contrast Light
ColorForeground=#545454
ColorBackground=#fcfcfc
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#fcfcfc;#800000;#008000;#808000;#000080;#800080;#008080;#545454;#c0c0c0;#800000;#008000;#808000;#000080;#800080;#008080;#000000
