# Scheme name: Equilibrium Gray Light
# Scheme author: Carlo Abelli
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Equilibrium Gray Light.16
ColorForeground=#474747
ColorBackground=#f1f1f1
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#e2e2e2;#d02023;#637200;#9d6f00;#0073b5;#c42775;#007a72;#303030;#f1f1f1;#bf3e05;#d4d4d4;#777777;#5e5e5e;#4e66b6;#474747;#1b1b1b
