# Scheme name: Equilibrium Gray Dark
# Scheme author: Carlo Abelli
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Equilibrium Gray Dark.16
ColorForeground=#ababab
ColorBackground=#111111
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#1b1b1b;#f04339;#7f8b00;#bb8801;#008dd1;#e3488e;#00948b;#c6c6c6;#111111;#df5923;#262626;#777777;#919191;#6a7fd2;#ababab;#e2e2e2
