# Scheme name: Gruvbox Material Light, Soft
# Scheme author: Mayush Kumar (https://github.com/MayushKumar), sainnhe (https://github.com/sainnhe/gruvbox-material-vscode)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Gruvbox Material Light, Soft.16
ColorForeground=#654735
ColorBackground=#f2e5bc
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#ebdbb2;#c14a4a;#6c782e;#b47109;#45707a;#e78a4e;#4c7a5d;#3c3836;#f2e5bc;#c35e0a;#c9b99a;#a89984;#665c54;#945e80;#654735;#282828
