# Scheme name: Ashes
# Scheme author: Jannik Siebert (https://github.com/janniks)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Ashes
ColorForeground=#c7ccd1
ColorBackground=#1c2023
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#1c2023;#c7ae95;#95c7ae;#aec795;#ae95c7;#c795ae;#95aec7;#c7ccd1;#747c84;#c7ae95;#95c7ae;#aec795;#ae95c7;#c795ae;#95aec7;#f3f4f5
