# Scheme name: Icy Dark
# Scheme author: icyphox (https://icyphox.ga)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Icy Dark.16
ColorForeground=#095b67
ColorBackground=#021012
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#031619;#16c1d9;#4dd0e1;#80deea;#00bcd4;#0097a7;#26c6da;#0c7c8c;#021012;#b3ebf2;#041f23;#052e34;#064048;#00acc1;#095b67;#109cb0
