# Scheme name: standardized-dark
# Scheme author: ali (https://github.com/ali-githb/base16-standardized-scheme)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-standardized-dark.16
ColorForeground=#c0c0c0
ColorBackground=#222222
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#303030;#e15d67;#5db129;#e1b31a;#00a3f2;#b87d28;#21c992;#e0e0e0;#222222;#fc804e;#555555;#898989;#898989;#b46ee0;#c0c0c0;#ffffff
