# Scheme name: iA Light
# Scheme author: iA Inc. (modified by aramisgithub)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-iA Light.16
ColorForeground=#181818
ColorBackground=#f6f6f6
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#dedede;#9c5a02;#38781c;#c48218;#48bac2;#8b6c37;#2d6bb1;#e8e8e8;#f6f6f6;#c43e18;#bde5f2;#898989;#767676;#a94598;#181818;#f8f8f8
