# Scheme name: Default Light
# Scheme author: Chris Kempson (http://chriskempson.com)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-default-light
ColorForeground=#383838
ColorBackground=#f8f8f8
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#f8f8f8;#ab4642;#a1b56c;#f7ca88;#7cafc2;#ba8baf;#86c1b9;#383838;#d8d8d8;#ab4642;#a1b56c;#f7ca88;#7cafc2;#ba8baf;#86c1b9;#181818
