# Scheme name: Brush Trees Dark
# Scheme author: Abraham White &lt;abelincoln.white@gmail.com&gt;
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Brush Trees Dark
ColorForeground=#b0c5c8
ColorBackground=#485867
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#485867;#b38686;#87b386;#aab386;#868cb3;#b386b2;#86b3b3;#b0c5c8;#8299a1;#b38686;#87b386;#aab386;#868cb3;#b386b2;#86b3b3;#e3efef
