# Scheme name: Aztec
# Scheme author: TheNeverMan (github.com/TheNeverMan)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Aztec.16
ColorForeground=#ffda51
ColorBackground=#101600
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#1a1e01;#ee2e00;#63d932;#eebb00;#5b4a9f;#a928b9;#3d94a5;#ffe178;#101600;#ee8800;#242604;#2e2e05;#ffd129;#883e9f;#ffda51;#ffeba0
