# Scheme name: Tokyo Night Light
# Scheme author: Michaël Ball
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Tokyo Night Light.16
ColorForeground=#343b59
ColorBackground=#d5d6db
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#cbccd1;#343b58;#485e30;#166775;#34548a;#8c4351;#3e6968;#1a1b26;#d5d6db;#965027;#dfe0e5;#9699a3;#4c505e;#5a4a78;#343b59;#1a1b26
