# Scheme name: Framer
# Scheme author: Framer (Maintained by Jesse Hoyos)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Framer.16
ColorForeground=#d0d0d0
ColorBackground=#181818
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#151515;#fd886b;#32ccdc;#fecb6e;#20bcfc;#b15f4a;#acddfd;#e8e8e8;#181818;#fc4769;#464646;#747474;#b9b9b9;#ba8cfc;#d0d0d0;#eeeeee
