# Scheme name: PaperColor Dark
# Scheme author: Jon Leopard (http://github.com/jonleopard), based on PaperColor Theme (https://github.com/NLKNguyen/papercolor-theme)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-papercolor-dark
ColorForeground=#808080
ColorBackground=#1c1c1c
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#1c1c1c;#585858;#af87d7;#afd700;#ff5faf;#00afaf;#ffaf00;#808080;#5faf00;#585858;#af87d7;#afd700;#ff5faf;#00afaf;#ffaf00;#d0d0d0
