# Scheme name: Equilibrium Dark
# Scheme author: Carlo Abelli
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Equilibrium Dark.16
ColorForeground=#afaba2
ColorBackground=#0c1118
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#181c22;#f04339;#7f8b00;#bb8801;#008dd1;#e3488e;#00948b;#cac6bd;#0c1118;#df5923;#22262d;#7b776e;#949088;#6a7fd2;#afaba2;#e7e2d9
