# Scheme name: Unikitty Reversible
# Scheme author: Josh W Lewis (@joshwlewis)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Unikitty Reversible.16
ColorForeground=#c3c2c4
ColorBackground=#2e2a31
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#4b484e;#d8137f;#17ad98;#dc8a0e;#7864fa;#d41acd;#149bda;#e1e0e1;#2e2a31;#d65407;#69666b;#878589;#a5a3a6;#b33ce8;#c3c2c4;#ffffff
