# Scheme name: Black Metal (Marduk)
# Scheme author: metalelf0 (https://github.com/metalelf0)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Black Metal (Marduk).16
ColorForeground=#c1c1c1
ColorBackground=#000000
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#121212;#5f8787;#a5aaa7;#626b67;#888888;#444444;#aaaaaa;#999999;#000000;#aaaaaa;#222222;#333333;#999999;#999999;#c1c1c1;#c1c1c1
