# Scheme name: Google Dark
# Scheme author: Seth Wright (http://sethawright.com)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Google Dark.16
ColorForeground=#c5c8c6
ColorBackground=#1d1f21
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#282a2e;#cc342b;#198844;#fba922;#3971ed;#3971ed;#3971ed;#e0e0e0;#1d1f21;#f96a38;#373b41;#969896;#b4b7b4;#a36ac7;#c5c8c6;#ffffff
