# Scheme name: Precious Light White
# Scheme author: 4lex4 &lt;4lex49@zoho.com&gt;
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Precious Light White.16
ColorForeground=#555555
ColorBackground=#ffffff
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#ededed;#af4947;#557301;#876500;#186daa;#a93e93;#087767;#555555;#ffffff;#a0570d;#dbdbdb;#848484;#636363;#7b4ecb;#555555;#555555
