# Scheme name: ShadeSmear Light
# Scheme author: Kyle Giammarco (http://kyle.giammar.co)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-ShadeSmear Light
ColorForeground=#232323
ColorBackground=#dbdbdb
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#dbdbdb;#cc5450;#71983b;#307878;#376388;#d7ab54;#c57d42;#232323;#4e4e4e;#cc5450;#71983b;#307878;#376388;#d7ab54;#c57d42;#e4e4e4
