# Scheme name: Solar Flare Light
# Scheme author: Chuck Harmston (https://chuck.harmston.ch)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Solar Flare Light.16
ColorForeground=#586875
ColorBackground=#f5f7fa
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#e8e9ed;#ef5253;#7cc844;#e4b51c;#33b5e1;#d73c9a;#52cbb0;#222e38;#f5f7fa;#e66b2b;#a6afb8;#85939e;#667581;#a363d5;#586875;#18262f
