# Scheme name: standardized-light
# Scheme author: ali (https://github.com/ali-githb/base16-standardized-scheme)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-standardized-light.16
ColorForeground=#444444
ColorBackground=#ffffff
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#eeeeee;#d03e3e;#31861f;#ad8200;#3173c5;#895025;#00998f;#333333;#ffffff;#d7691d;#cccccc;#767676;#767676;#9e57c2;#444444;#222222
