# Scheme name: Rosé Pine Dawn
# Scheme author: Emilia Dunfelt &lt;edun@dunfelt.se&gt;
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Rosé Pine Dawn
ColorForeground=#575279
ColorBackground=#faf4ed
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#faf4ed;#b4637a;#286983;#d7827e;#907aa9;#ea9d34;#56949f;#575279;#9893a5;#b4637a;#286983;#d7827e;#907aa9;#ea9d34;#56949f;#cecacd
