# Scheme name: Moonlight
# Scheme author: Jeremy Swinarton (https://github.com/jswinarton)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Moonlight
ColorForeground=#a3ace1
ColorBackground=#212337
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#212337;#ff5370;#2df4c0;#ffc777;#40ffff;#b994f1;#04d1f9;#a3ace1;#748cd6;#ff5370;#2df4c0;#ffc777;#40ffff;#b994f1;#04d1f9;#ef43fa
