# Scheme name: Grayscale Dark
# Scheme author: Alexandre Gavioli (https://github.com/Alexx2/)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Grayscale Dark.16
ColorForeground=#b9b9b9
ColorBackground=#101010
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#252525;#7c7c7c;#8e8e8e;#a0a0a0;#686868;#5e5e5e;#868686;#e3e3e3;#101010;#999999;#464646;#525252;#ababab;#747474;#b9b9b9;#f7f7f7
