# Scheme name: Windows 95
# Scheme author: Fergus Collins (https://github.com/C-Fergus)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Windows 95.16
ColorForeground=#a8a8a8
ColorBackground=#000000
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#1c1c1c;#fc5454;#54fc54;#fcfc54;#5454fc;#00a800;#54fcfc;#d2d2d2;#000000;#a85400;#383838;#545454;#7e7e7e;#fc54fc;#a8a8a8;#fcfcfc
