# Scheme name: Tokyo Night Terminal Dark
# Scheme author: Michaël Ball
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Tokyo Night Terminal Dark.16
ColorForeground=#787c99
ColorBackground=#16161e
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#1a1b26;#f7768e;#41a6b5;#e0af68;#7aa2f7;#d18616;#7dcfff;#cbccd1;#16161e;#ff9e64;#2f3549;#444b6a;#787c99;#bb9af7;#787c99;#d5d6db
