# Scheme name: Mountain
# Scheme author: gnsfujiwara (https://github.com/gnsfujiwara) based on Mountain Theme (https://github.com/mountain-theme/Mountain)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Mountain.16
ColorForeground=#f0f0f0
ColorBackground=#0f0f0f
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#191919;#ac8a8c;#8aac8b;#aca98a;#8f8aac;#ac8a8c;#8aabac;#e7e7e7;#0f0f0f;#ceb188;#262626;#4c4c4c;#ac8a8c;#ac8aac;#f0f0f0;#cacaca
