# Scheme name: Harmonic16 Light
# Scheme author: Jannik Siebert (https://github.com/janniks)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Harmonic16 Light.16
ColorForeground=#405c79
ColorBackground=#f7f9fb
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#e5ebf1;#bf8b56;#56bf8b;#8bbf56;#8b56bf;#bf5656;#568bbf;#223b54;#f7f9fb;#bfbf56;#cbd6e2;#aabcce;#627e99;#bf568b;#405c79;#0b1c2c
