# Scheme name: Equilibrium Light
# Scheme author: Carlo Abelli
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Equilibrium Light.16
ColorForeground=#43474e
ColorBackground=#f5f0e7
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#e7e2d9;#d02023;#637200;#9d6f00;#0073b5;#c42775;#007a72;#2c3138;#f5f0e7;#bf3e05;#d8d4cb;#73777f;#5a5f66;#4e66b6;#43474e;#181c22
