# Scheme name: Catppuccin
# Scheme author: Pocco81 (https://github.com/pocco81)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Catppuccin
ColorForeground=#d7dae0
ColorBackground=#1e1e28
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#1e1e28;#f28fad;#abe9b3;#fae3b0;#96cdfb;#ddb6f2;#b5e8e0;#d7dae0;#575268;#f28fad;#abe9b3;#fae3b0;#96cdfb;#ddb6f2;#b5e8e0;#c9cbff
