# Scheme name: Woodland
# Scheme author: Jay Cornwall (https://jcornwall.com)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-woodland
ColorForeground=#cabcb1
ColorBackground=#231e18
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#231e18;#d35c5c;#b7ba53;#e0ac16;#88a4d3;#bb90e2;#6eb958;#cabcb1;#48413a;#d35c5c;#b7ba53;#e0ac16;#88a4d3;#bb90e2;#6eb958;#e4d4c8
