# Scheme name: Summerfruit Light
# Scheme author: Christopher Corley (http://christop.club/)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Summerfruit Light.16
ColorForeground=#101010
ColorBackground=#ffffff
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#e0e0e0;#ff0086;#00c918;#aba800;#3777e6;#cc6633;#1faaaa;#151515;#ffffff;#fd8900;#d0d0d0;#b0b0b0;#000000;#ad00a1;#101010;#202020
