# Scheme name: pinky
# Scheme author: Benjamin (https://github.com/b3nj5m1n)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-pinky.16
ColorForeground=#f5f5f5
ColorBackground=#171517
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#1b181b;#ffa600;#ff0066;#20df6c;#00ffff;#df206c;#6600ff;#ffffff;#171517;#00ff66;#1d1b1d;#383338;#e7dbdb;#007fff;#f5f5f5;#f7f3f7
