# Scheme name: Kimber
# Scheme author: Mishka Nguyen (https://github.com/akhsiM)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Kimber.16
ColorForeground=#dedee7
ColorBackground=#222222
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#313131;#c88c8c;#99c899;#d8b56d;#537c9c;#704f4f;#78b4b4;#c3c3b4;#222222;#476c88;#555d55;#644646;#5a5a5a;#86cacd;#dedee7;#ffffe6
