# Scheme name: Precious Dark Eleven
# Scheme author: 4lex4 &lt;4lex49@zoho.com&gt;
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Precious Dark Eleven.16
ColorForeground=#b8b7b6
ColorBackground=#1c1e20
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#292b2d;#ff8782;#95b658;#d0a543;#68b0ee;#f382d8;#42bda7;#b8b7b6;#1c1e20;#ea9755;#37393a;#858585;#a8a8a7;#b799fe;#b8b7b6;#b8b7b6
