# Scheme name: Mountain
# Scheme author: gnsfujiwara (https://github.com/gnsfujiwara)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Mountain
ColorForeground=#cacaca
ColorBackground=#0f0f0f
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#0f0f0f;#ac8a8c;#8aac8b;#aca98a;#8f8aac;#ac8aac;#8aabac;#cacaca;#4c4c4c;#ac8a8c;#8aac8b;#aca98a;#8f8aac;#ac8aac;#8aabac;#f0f0f0
