# Scheme name: Still Alive
# Scheme author: Derrick McKee (derrick.mckee@gmail.com)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-still-alive
ColorForeground=#d80000
ColorBackground=#f0f0f0
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#f0f0f0;#487830;#5c5c6a;#426395;#001878;#900000;#2c3c57;#d80000;#fff018;#487830;#5c5c6a;#426395;#001878;#900000;#2c3c57;#30a860
