# Scheme name: Catppuccin Macchiato
# Scheme author: https://github.com/catppuccin/catppuccin
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Catppuccin Macchiato
ColorForeground=#cad3f5
ColorBackground=#24273a
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#24273a;#ed8796;#a6da95;#eed49f;#8aadf4;#c6a0f6;#8bd5ca;#cad3f5;#494d64;#ed8796;#a6da95;#eed49f;#8aadf4;#c6a0f6;#8bd5ca;#b7bdf8
