# Scheme name: Tango
# Scheme author: @Schnouki, based on the Tango Desktop Project
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Tango.16
ColorForeground=#d3d7cf
ColorBackground=#2e3436
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#8ae234;#cc0000;#4e9a06;#c4a000;#3465a4;#34e2e2;#06989a;#ad7fa8;#2e3436;#ef2929;#fce94f;#555753;#729fcf;#75507b;#d3d7cf;#eeeeec
