# Scheme name: Classic Light
# Scheme author: Jason Heeris (http://heeris.id.au)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Classic Light
ColorForeground=#303030
ColorBackground=#f5f5f5
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#f5f5f5;#ac4142;#90a959;#f4bf75;#6a9fb5;#aa759f;#75b5aa;#303030;#b0b0b0;#ac4142;#90a959;#f4bf75;#6a9fb5;#aa759f;#75b5aa;#151515
