# Scheme name: Edge Light
# Scheme author: cjayross (https://github.com/cjayross)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Edge Light.16
ColorForeground=#5e646f
ColorBackground=#fafafa
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#7c9f4b;#db7070;#7c9f4b;#d69822;#6587bf;#509c93;#509c93;#b870ce;#fafafa;#db7070;#d69822;#5e646f;#6587bf;#b870ce;#5e646f;#5e646f
