# Scheme name: Macintosh
# Scheme author: Rebecca Bettencourt (http://www.kreativekorp.com)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Macintosh.16
ColorForeground=#c0c0c0
ColorBackground=#000000
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#404040;#dd0907;#1fb714;#fbf305;#0000d3;#90713a;#02abea;#c0c0c0;#000000;#ff6403;#404040;#808080;#808080;#4700a5;#c0c0c0;#ffffff
