# Scheme name: Apathy
# Scheme author: Jannik Siebert (https://github.com/janniks)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Apathy.16
ColorForeground=#81b5ac
ColorBackground=#031a16
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#0b342d;#3e9688;#883e96;#3e4c96;#96883e;#3e965b;#963e4c;#a7cec8;#031a16;#3e7996;#184e45;#2b685e;#5f9c92;#4c963e;#81b5ac;#d2e7e4
