# Scheme name: Primer Light
# Scheme author: Jimmy Lin
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-primer-light
ColorForeground=#2f363d
ColorBackground=#fafbfc
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#fafbfc;#d73a49;#28a745;#ffd33d;#0366d6;#ea4aaa;#79b8ff;#2f363d;#d1d5da;#d73a49;#28a745;#ffd33d;#0366d6;#ea4aaa;#79b8ff;#1b1f23
