# Scheme name: Kanagawa
# Scheme author: Tommaso Laurenzi (https://github.com/rebelot)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Kanagawa.16
ColorForeground=#dcd7ba
ColorBackground=#1f1f28
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#16161d;#c34043;#76946a;#c0a36e;#7e9cd8;#d27e99;#6a9589;#c8c093;#1f1f28;#ffa066;#223249;#54546d;#727169;#957fb8;#dcd7ba;#717c7c
