# Scheme name: Ayu Dark
# Scheme author: Khue Nguyen &lt;Z5483Y@gmail.com&gt;
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Ayu Dark.16
ColorForeground=#e6e1cf
ColorBackground=#0f1419
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#131721;#f07178;#b8cc52;#ffb454;#59c2ff;#e6b673;#95e6cb;#e6e1cf;#0f1419;#ff8f40;#272d38;#3e4b59;#bfbdb6;#d2a6ff;#e6e1cf;#f3f4f5
