# Scheme name: Da One Sea
# Scheme author: NNB (https://github.com/NNBnh)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Da One Sea.16
ColorForeground=#ffffff
ColorBackground=#22273d
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#374059;#fa7883;#98c379;#ff9470;#6bb8ff;#b3684f;#8af5ff;#ffffff;#22273d;#ffc387;#525866;#878d96;#c8c8c8;#e799ff;#ffffff;#ffffff
