# Scheme name: Gruvbox Material Dark, Hard
# Scheme author: Mayush Kumar (https://github.com/MayushKumar), sainnhe (https://github.com/sainnhe/gruvbox-material-vscode)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Gruvbox Material Dark, Hard
ColorForeground=#ddc7a1
ColorBackground=#202020
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#202020;#ea6962;#a9b665;#d8a657;#7daea3;#d3869b;#89b482;#ddc7a1;#5a524c;#ea6962;#a9b665;#d8a657;#7daea3;#d3869b;#89b482;#fbf1c7
