# Scheme name: Terracotta Dark
# Scheme author: Alexander Rossell Hayes (https://github.com/rossellhayes)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Terracotta Dark.16
ColorForeground=#b8a59d
ColorBackground=#241d1a
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#362b27;#f6998f;#b6c68a;#ffc37a;#b0a4c3;#f1ae97;#c0bcdb;#cabbb5;#241d1a;#ffa888;#473933;#594740;#a78e84;#d8a2b0;#b8a59d;#dcd2ce
