# Scheme name: Tokyodark
# Scheme author: Tiagovla (https://github.com/tiagovla/)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Tokyodark.16
ColorForeground=#abb2bf
ColorBackground=#11121d
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#151621;#a485dd;#d7a65f;#7199ee;#95c561;#773440;#a485dd;#555661;#11121d;#a485dd;#43444f;#393a45;#1b1c27;#ee6d85;#abb2bf;#2c2d38
