# Scheme name: Tomorrow
# Scheme author: Chris Kempson (http://chriskempson.com)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Tomorrow
ColorForeground=#4d4d4c
ColorBackground=#ffffff
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#ffffff;#c82829;#718c00;#eab700;#4271ae;#8959a8;#3e999f;#4d4d4c;#8e908c;#c82829;#718c00;#eab700;#4271ae;#8959a8;#3e999f;#1d1f21
