# Scheme name: Default Light
# Scheme author: Chris Kempson (http://chriskempson.com)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Default Light.16
ColorForeground=#383838
ColorBackground=#f8f8f8
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#e8e8e8;#ab4642;#a1b56c;#f7ca88;#7cafc2;#a16946;#86c1b9;#282828;#f8f8f8;#dc9656;#d8d8d8;#b8b8b8;#585858;#ba8baf;#383838;#181818
