# Scheme name: Atelier Forest Light
# Scheme author: Bram de Haan (http://atelierbramdehaan.nl)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Atelier Forest Light.16
ColorForeground=#68615e
ColorBackground=#f1efee
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#e6e2e0;#f22c40;#7b9726;#c38418;#407ee7;#c33ff3;#3d97b8;#2c2421;#f1efee;#df5320;#a8a19f;#9c9491;#766e6b;#6666ea;#68615e;#1b1918
