# Scheme name: Monokai
# Scheme author: Wimer Hazenberg (http://www.monokai.nl)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Monokai.16
ColorForeground=#f8f8f2
ColorBackground=#272822
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#383830;#f92672;#a6e22e;#f4bf75;#66d9ef;#cc6633;#a1efe4;#f5f4f1;#272822;#fd971f;#49483e;#75715e;#a59f85;#ae81ff;#f8f8f2;#f9f8f5
