# Scheme name: Ashes
# Scheme author: Jannik Siebert (https://github.com/janniks)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Ashes.16
ColorForeground=#c7ccd1
ColorBackground=#1c2023
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#393f45;#c7ae95;#95c7ae;#aec795;#ae95c7;#c79595;#95aec7;#dfe2e5;#1c2023;#c7c795;#565e65;#747c84;#adb3ba;#c795ae;#c7ccd1;#f3f4f5
