# Scheme name: Atelier Plateau Light
# Scheme author: Bram de Haan (http://atelierbramdehaan.nl)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Atelier Plateau Light.16
ColorForeground=#585050
ColorBackground=#f4ecec
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#e7dfdf;#ca4949;#4b8b8b;#a06e3b;#7272ca;#bd5187;#5485b6;#292424;#f4ecec;#b45a3c;#8a8585;#7e7777;#655d5d;#8464c4;#585050;#1b1818
