# Scheme name: Still Alive
# Scheme author: Derrick McKee (derrick.mckee@gmail.com)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Still Alive.16
ColorForeground=#d80000
ColorBackground=#f0f0f0
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#f0d848;#487830;#5c5c6a;#426395;#001878;#140c0d;#2c3c57;#489000;#f0f0f0;#183048;#fff018;#f01818;#f00000;#900000;#d80000;#30a860
