# Scheme name: Horizon Light
# Scheme author: Michaël Ball (http://github.com/michael-ball/)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Horizon Light.16
ColorForeground=#403c3d
ColorBackground=#fdf0ed
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#fadad1;#f7939b;#94e1b0;#fbe0d9;#da103f;#e58c92;#dc3318;#302c2d;#fdf0ed;#f6661e;#f9cbbe;#bdb3b1;#948c8a;#1d8991;#403c3d;#201c1d
