# Scheme name: Da One Gray
# Scheme author: NNB (https://github.com/NNBnh)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Da One Gray.16
ColorForeground=#ffffff
ColorBackground=#181818
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#282828;#fa7883;#98c379;#ff9470;#6bb8ff;#b3684f;#8af5ff;#ffffff;#181818;#ffc387;#585858;#888888;#c8c8c8;#e799ff;#ffffff;#ffffff
