# Scheme name: iA Dark
# Scheme author: iA Inc. (modified by aramisgithub)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-iA Dark.16
ColorForeground=#cccccc
ColorBackground=#1a1a1a
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#222222;#d88568;#83a471;#b99353;#8eccdd;#8b6c37;#7c9cae;#e8e8e8;#1a1a1a;#d86868;#1d414d;#767676;#b8b8b8;#b98eb2;#cccccc;#f8f8f8
