# Scheme name: Gruvbox Material Dark, Hard
# Scheme author: Mayush Kumar (https://github.com/MayushKumar), sainnhe (https://github.com/sainnhe/gruvbox-material-vscode)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Gruvbox Material Dark, Hard.16
ColorForeground=#ddc7a1
ColorBackground=#202020
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#2a2827;#ea6962;#a9b665;#d8a657;#7daea3;#bd6f3e;#89b482;#ebdbb2;#202020;#e78a4e;#504945;#5a524c;#bdae93;#d3869b;#ddc7a1;#fbf1c7
