# Scheme name: Windows 95 Light
# Scheme author: Fergus Collins (https://github.com/C-Fergus)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Windows 95 Light.16
ColorForeground=#545454
ColorBackground=#fcfcfc
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#e0e0e0;#a80000;#00a800;#a85400;#0000a8;#54fc54;#00a8a8;#2a2a2a;#fcfcfc;#fcfc54;#c4c4c4;#a8a8a8;#7e7e7e;#a800a8;#545454;#000000
