# Scheme name: Marrakesh
# Scheme author: Alexandre Gavioli (http://github.com/Alexx2/)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Marrakesh.16
ColorForeground=#948e48
ColorBackground=#201602
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#302e00;#c35359;#18974e;#a88339;#477ca1;#b3588e;#75a738;#ccc37a;#201602;#b36144;#5f5b17;#6c6823;#86813b;#8868b3;#948e48;#faf0a5
