# Scheme name: Blue Forest
# Scheme author: alonsodomin (https://github.com/alonsodomin)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Blue Forest.16
ColorForeground=#ffcc33
ColorBackground=#141f2e
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#1e5c1e;#fffab1;#80ff80;#91ccff;#a2cff5;#e7e7e7;#80ff80;#91ccff;#141f2e;#ff8080;#273e5c;#a0ffa0;#1e5c1e;#0099ff;#ffcc33;#375780
