# Scheme name: Nord Light
# Scheme author: threddast, based on fuxialexander&#39;s doom-nord-light-theme (Doom Emacs)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Nord Light.16
ColorForeground=#2e3440
ColorBackground=#e5e9f0
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#c2d0e7;#99324b;#4f894c;#9a7500;#3b6ea8;#5272af;#398eac;#3b4252;#e5e9f0;#ac4426;#b8c5db;#aebacf;#60728c;#97365b;#2e3440;#29838d
