# Scheme name: Tokyo Night Terminal Light
# Scheme author: Michaël Ball
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Tokyo Night Terminal Light
ColorForeground=#4c505e
ColorBackground=#d5d6db
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#d5d6db;#8c4351;#33635c;#8f5e15;#34548a;#5a4a78;#0f4b6e;#4c505e;#9699a3;#8c4351;#33635c;#8f5e15;#34548a;#5a4a78;#0f4b6e;#1a1b26
