# Scheme name: Pasque
# Scheme author: Gabriel Fontes (https://github.com/Misterio77)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Pasque.16
ColorForeground=#dedcdf
ColorBackground=#271c3a
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#100323;#a92258;#c6914b;#804ead;#8e7dc6;#59325c;#7263aa;#edeaef;#271c3a;#918889;#3e2d5c;#5d5766;#bebcbf;#953b9d;#dedcdf;#bbaadd
