# Scheme name: Catppuccin Frappe
# Scheme author: https://github.com/catppuccin/catppuccin
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Catppuccin Frappe
ColorForeground=#c6d0f5
ColorBackground=#303446
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#303446;#e78284;#a6d189;#e5c890;#8caaee;#ca9ee6;#81c8be;#c6d0f5;#51576d;#e78284;#a6d189;#e5c890;#8caaee;#ca9ee6;#81c8be;#babbf1
