# Scheme name: Windows 95
# Scheme author: Fergus Collins (https://github.com/C-Fergus)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-windows-95
ColorForeground=#a8a8a8
ColorBackground=#000000
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#000000;#fc5454;#54fc54;#fcfc54;#5454fc;#fc54fc;#54fcfc;#a8a8a8;#383838;#fc5454;#54fc54;#fcfc54;#5454fc;#fc54fc;#54fcfc;#fcfcfc
