# Scheme name: Ayu Mirage
# Scheme author: Khue Nguyen &lt;Z5483Y@gmail.com&gt;
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Ayu Mirage.16
ColorForeground=#cccac2
ColorBackground=#171b24
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#1f2430;#f28779;#d5ff80;#ffd173;#5ccfe6;#f29e74;#95e6cb;#d9d7ce;#171b24;#ffad66;#242936;#707a8c;#8a9199;#d4bfff;#cccac2;#f3f4f5
