# Scheme name: Horizon Dark
# Scheme author: Michaël Ball (http://github.com/michael-ball/)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Horizon Dark.16
ColorForeground=#cbced0
ColorBackground=#1c1e26
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#232530;#e93c58;#efaf8e;#efb993;#df5273;#e4a382;#24a8b4;#dcdfe4;#1c1e26;#e58d7d;#2e303e;#6f6f70;#9da0a2;#b072d1;#cbced0;#e3e6ee
