# Scheme name: Nova
# Scheme author: George Essig (https://github.com/gessig), Trevor D. Miller (https://trevordmiller.com)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Nova.16
ColorForeground=#c5d4dd
ColorBackground=#3c4c55
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#556873;#83afe5;#7fc1ca;#a8ce93;#83afe5;#f2c38f;#f2c38f;#899ba6;#3c4c55;#7fc1ca;#6a7d89;#899ba6;#899ba6;#9a93e1;#c5d4dd;#556873
