# Scheme name: Gruvbox light, hard
# Scheme author: Dawid Kurek (dawikur@gmail.com), morhetz (https://github.com/morhetz/gruvbox)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Gruvbox light, hard
ColorForeground=#504945
ColorBackground=#f9f5d7
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#f9f5d7;#9d0006;#79740e;#b57614;#076678;#8f3f71;#427b58;#504945;#bdae93;#9d0006;#79740e;#b57614;#076678;#8f3f71;#427b58;#282828
