# Scheme name: Grayscale Light
# Scheme author: Alexandre Gavioli (https://github.com/Alexx2/)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Grayscale Light.16
ColorForeground=#464646
ColorBackground=#f7f7f7
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#e3e3e3;#7c7c7c;#8e8e8e;#a0a0a0;#686868;#5e5e5e;#868686;#252525;#f7f7f7;#999999;#b9b9b9;#ababab;#525252;#747474;#464646;#101010
