# Scheme name: Sakura
# Scheme author: Misterio77 (http://github.com/Misterio77)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Sakura.16
ColorForeground=#564448
ColorBackground=#feedf3
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#f8e2e7;#df2d52;#2e916d;#c29461;#006e93;#ba0d35;#1d8991;#42383a;#feedf3;#f6661e;#e0ccd1;#755f64;#665055;#5e2180;#564448;#33292b
