# Scheme name: Tokyo City Terminal Dark
# Scheme author: Michaël Ball
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Tokyo City Terminal Dark.16
ColorForeground=#d8e2ec
ColorBackground=#171d23
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#1d252c;#d95468;#8bd49c;#ebbf83;#539afc;#dd9d82;#70e1e8;#f6f6f8;#171d23;#ff9e64;#28323a;#526270;#b7c5d3;#b62d65;#d8e2ec;#fbfbfd
