# Scheme name: Tokyo Night Dark
# Scheme author: Michaël Ball
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Tokyo Night Dark.16
ColorForeground=#a9b1d6
ColorBackground=#1a1b26
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#16161e;#c0caf5;#9ece6a;#0db9d7;#2ac3de;#f7768e;#b4f9f8;#cbccd1;#1a1b26;#a9b1d6;#2f3549;#444b6a;#787c99;#bb9af7;#a9b1d6;#d5d6db
