# Scheme name: Harmonic16 Light
# Scheme author: Jannik Siebert (https://github.com/janniks)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Harmonic16 Light
ColorForeground=#405c79
ColorBackground=#f7f9fb
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#f7f9fb;#bf8b56;#56bf8b;#8bbf56;#8b56bf;#bf568b;#568bbf;#405c79;#aabcce;#bf8b56;#56bf8b;#8bbf56;#8b56bf;#bf568b;#568bbf;#0b1c2c
