# Scheme name: Macintosh
# Scheme author: Rebecca Bettencourt (http://www.kreativekorp.com)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Macintosh
ColorForeground=#c0c0c0
ColorBackground=#000000
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#000000;#dd0907;#1fb714;#fbf305;#0000d3;#4700a5;#02abea;#c0c0c0;#808080;#dd0907;#1fb714;#fbf305;#0000d3;#4700a5;#02abea;#ffffff
