# Scheme name: Classic Light
# Scheme author: Jason Heeris (http://heeris.id.au)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Classic Light.16
ColorForeground=#303030
ColorBackground=#f5f5f5
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#e0e0e0;#ac4142;#90a959;#f4bf75;#6a9fb5;#8f5536;#75b5aa;#202020;#f5f5f5;#d28445;#d0d0d0;#b0b0b0;#505050;#aa759f;#303030;#151515
