# Scheme name: Classic Dark
# Scheme author: Jason Heeris (http://heeris.id.au)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Classic Dark.16
ColorForeground=#d0d0d0
ColorBackground=#151515
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#202020;#ac4142;#90a959;#f4bf75;#6a9fb5;#8f5536;#75b5aa;#e0e0e0;#151515;#d28445;#303030;#505050;#b0b0b0;#aa759f;#d0d0d0;#f5f5f5
