# Scheme name: Gruvbox dark, medium
# Scheme author: Dawid Kurek (dawikur@gmail.com), morhetz (https://github.com/morhetz/gruvbox)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-gruvbox-dark-medium
ColorForeground=#d5c4a1
ColorBackground=#282828
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#282828;#fb4934;#b8bb26;#fabd2f;#83a598;#d3869b;#8ec07c;#d5c4a1;#504945;#fb4934;#b8bb26;#fabd2f;#83a598;#d3869b;#8ec07c;#fbf1c7
