# Scheme name: Atelier Forest Light
# Scheme author: Bram de Haan (http://atelierbramdehaan.nl)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Atelier Forest Light
ColorForeground=#68615e
ColorBackground=#f1efee
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#f1efee;#f22c40;#7b9726;#c38418;#407ee7;#6666ea;#3d97b8;#68615e;#9c9491;#f22c40;#7b9726;#c38418;#407ee7;#6666ea;#3d97b8;#1b1918
