# Scheme name: Atelier Dune
# Scheme author: Bram de Haan (http://atelierbramdehaan.nl)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Atelier Dune.16
ColorForeground=#a6a28c
ColorBackground=#20201d
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#292824;#d73737;#60ac39;#ae9513;#6684e1;#d43552;#1fad83;#e8e4cf;#20201d;#b65611;#6e6b5e;#7d7a68;#999580;#b854d4;#a6a28c;#fefbec
