# Scheme name: Material Palenight
# Scheme author: Nate Peterson
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Material Palenight
ColorForeground=#959dcb
ColorBackground=#292d3e
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#292d3e;#f07178;#c3e88d;#ffcb6b;#82aaff;#c792ea;#89ddff;#959dcb;#676e95;#f07178;#c3e88d;#ffcb6b;#82aaff;#c792ea;#89ddff;#ffffff
