# Scheme name: OceanicNext
# Scheme author: https://github.com/voronianski/oceanic-next-color-scheme
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-OceanicNext.16
ColorForeground=#c0c5ce
ColorBackground=#1b2b34
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#343d46;#ec5f67;#99c794;#fac863;#6699cc;#ab7967;#5fb3b3;#cdd3de;#1b2b34;#f99157;#4f5b66;#65737e;#a7adba;#c594c5;#c0c5ce;#d8dee9
