# Scheme name: Tokyodark
# Scheme author: Jamy Golden (https://github.com/JamyGolden), Based on Tokyodark.nvim (https://github.com/tiagovla/tokyodark.nvim)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Tokyodark.16
ColorForeground=#a0a8cd
ColorBackground=#11121d
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#212234;#ee6d85;#95c561;#d7a65f;#7199ee;#773440;#9fbbf3;#abb2bf;#11121d;#f6955b;#212234;#353945;#4a5057;#a485dd;#a0a8cd;#bcc2dc
