# Scheme name: Gruvbox Material Light, Medium
# Scheme author: Mayush Kumar (https://github.com/MayushKumar), sainnhe (https://github.com/sainnhe/gruvbox-material-vscode)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Gruvbox Material Light, Medium
ColorForeground=#654735
ColorBackground=#fbf1c7
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#fbf1c7;#c14a4a;#6c782e;#b47109;#45707a;#945e80;#4c7a5d;#654735;#bdae93;#c14a4a;#6c782e;#b47109;#45707a;#945e80;#4c7a5d;#282828
