# Scheme name: Material Palenight
# Scheme author: Nate Peterson
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Material Palenight.16
ColorForeground=#959dcb
ColorBackground=#292d3e
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#444267;#f07178;#c3e88d;#ffcb6b;#82aaff;#ff5370;#89ddff;#959dcb;#292d3e;#f78c6c;#32374d;#676e95;#8796b0;#c792ea;#959dcb;#ffffff
