# Scheme name: Classic Light
# Scheme author: Jason Heeris (http://heeris.id.au)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-classic-light
ColorForeground=#303030
ColorBackground=#f5f5f5
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#f5f5f5;#ac4142;#90a959;#f4bf75;#6a9fb5;#aa759f;#75b5aa;#303030;#d0d0d0;#ac4142;#90a959;#f4bf75;#6a9fb5;#aa759f;#75b5aa;#151515
