# Scheme name: Brogrammer
# Scheme author: Vik Ramanujam (http://github.com/piggyslasher)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Brogrammer.16
ColorForeground=#4e5ab7
ColorBackground=#1f1f1f
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#f81118;#d6dbe5;#f3bd09;#1dd361;#5350b9;#ffffff;#1081d6;#1081d6;#1f1f1f;#de352e;#2dc55e;#ecba0f;#2a84d2;#0f7ddb;#4e5ab7;#d6dbe5
