# Scheme name: selenized-dark
# Scheme author: Jan Warchol (https://github.com/jan-warchol/selenized) / adapted to base16 by ali
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-selenized-dark.16
ColorForeground=#adbcbc
ColorBackground=#103c48
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#184956;#fa5750;#75b938;#dbb32d;#4695f7;#f275be;#41c7b9;#cad8d9;#103c48;#ed8649;#2d5b69;#72898f;#72898f;#af88eb;#adbcbc;#cad8d9
