# Scheme name: XCode Dusk
# Scheme author: Elsa Gonsiorowski (https://github.com/gonsie)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-xcode-dusk
ColorForeground=#939599
ColorBackground=#282b35
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#282b35;#b21889;#df0002;#438288;#790ead;#b21889;#00a0be;#939599;#53555d;#b21889;#df0002;#438288;#790ead;#b21889;#00a0be;#bebfc2
