# Scheme name: Gruvbox light, medium
# Scheme author: Dawid Kurek (dawikur@gmail.com), morhetz (https://github.com/morhetz/gruvbox)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Gruvbox light, medium.16
ColorForeground=#504945
ColorBackground=#fbf1c7
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#ebdbb2;#9d0006;#79740e;#b57614;#076678;#d65d0e;#427b58;#3c3836;#fbf1c7;#af3a03;#d5c4a1;#bdae93;#665c54;#8f3f71;#504945;#282828
