# Scheme name: Ocean
# Scheme author: Chris Kempson (http://chriskempson.com)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Ocean.16
ColorForeground=#c0c5ce
ColorBackground=#2b303b
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#343d46;#bf616a;#a3be8c;#ebcb8b;#8fa1b3;#ab7967;#96b5b4;#dfe1e8;#2b303b;#d08770;#4f5b66;#65737e;#a7adba;#b48ead;#c0c5ce;#eff1f5
