# Scheme name: Edge Dark
# Scheme author: cjayross (https://github.com/cjayross)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Edge Dark.16
ColorForeground=#b7bec9
ColorBackground=#262729
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#88909f;#e77171;#a1bf78;#dbb774;#73b3e7;#5ebaa5;#5ebaa5;#d390e7;#262729;#e77171;#b7bec9;#3e4249;#73b3e7;#d390e7;#b7bec9;#3e4249
