# Scheme name: Gruvbox dark, hard
# Scheme author: Dawid Kurek (dawikur@gmail.com), morhetz (https://github.com/morhetz/gruvbox)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Gruvbox dark, hard
ColorForeground=#d5c4a1
ColorBackground=#1d2021
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#1d2021;#fb4934;#b8bb26;#fabd2f;#83a598;#d3869b;#8ec07c;#d5c4a1;#665c54;#fb4934;#b8bb26;#fabd2f;#83a598;#d3869b;#8ec07c;#fbf1c7
