# Scheme name: Da One White
# Scheme author: NNB (https://github.com/NNBnh)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Da One White.16
ColorForeground=#181818
ColorBackground=#ffffff
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#c8c8c8;#de5d6e;#76a85d;#b3684f;#5890f8;#b3684f;#64b5a7;#000000;#ffffff;#ff9470;#888888;#585858;#282828;#c173d1;#181818;#000000
