# Scheme name: Windows High Contrast
# Scheme author: Fergus Collins (https://github.com/C-Fergus)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Windows High Contrast
ColorForeground=#c0c0c0
ColorBackground=#000000
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#000000;#fc5454;#54fc54;#fcfc54;#5454fc;#fc54fc;#54fcfc;#c0c0c0;#545454;#fc5454;#54fc54;#fcfc54;#5454fc;#fc54fc;#54fcfc;#fcfcfc
