# Scheme name: Horizon Terminal Dark
# Scheme author: Michaël Ball (http://github.com/michael-ball/)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Horizon Terminal Dark
ColorForeground=#cbced0
ColorBackground=#1c1e26
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#1c1e26;#e95678;#29d398;#fac29a;#26bbd9;#ee64ac;#59e1e3;#cbced0;#6f6f70;#e95678;#29d398;#fac29a;#26bbd9;#ee64ac;#59e1e3;#e3e6ee
