# Scheme name: Horizon Terminal Light
# Scheme author: Michaël Ball (http://github.com/michael-ball/)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Horizon Terminal Light.16
ColorForeground=#403c3d
ColorBackground=#fdf0ed
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#fadad1;#e95678;#29d398;#fadad1;#26bbd9;#f9cbbe;#59e1e3;#302c2d;#fdf0ed;#f9cec3;#f9cbbe;#bdb3b1;#948c8a;#ee64ac;#403c3d;#201c1d
