# Scheme name: Atelier Lakeside
# Scheme author: Bram de Haan (http://atelierbramdehaan.nl)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Atelier Lakeside.16
ColorForeground=#7ea2b4
ColorBackground=#161b1d
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#1f292e;#d22d72;#568c3b;#8a8a0f;#257fad;#b72dd2;#2d8f6f;#c1e4f6;#161b1d;#935c25;#516d7b;#5a7b8c;#7195a8;#6b6bb8;#7ea2b4;#ebf8ff
