# Scheme name: Gruvbox Material Dark, Soft
# Scheme author: Mayush Kumar (https://github.com/MayushKumar), sainnhe (https://github.com/sainnhe/gruvbox-material-vscode)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Gruvbox Material Dark, Soft.16
ColorForeground=#ddc7a1
ColorBackground=#32302f
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#3c3836;#ea6962;#a9b665;#d8a657;#7daea3;#bd6f3e;#89b482;#ebdbb2;#32302f;#e78a4e;#5a524c;#7c6f64;#bdae93;#d3869b;#ddc7a1;#fbf1c7
