# Scheme name: UwUnicorn
# Scheme author: Fernando Marques (https://github.com/RakkiUwU) and Gabriel Fontes (https://github.com/Misterio77)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-UwUnicorn.16
ColorForeground=#eed5d9
ColorBackground=#241b26
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#2f2a3f;#877bb6;#c965bf;#a84a73;#6a9eb5;#a3a079;#9c5fce;#d9c2c6;#241b26;#de5b44;#46354a;#6c3cb2;#7e5f83;#78a38f;#eed5d9;#e4ccd0
