# Scheme name: Flat
# Scheme author: Chris Kempson (http://chriskempson.com)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Flat.16
ColorForeground=#e0e0e0
ColorBackground=#2c3e50
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#34495e;#e74c3c;#2ecc71;#f1c40f;#3498db;#be643c;#1abc9c;#f5f5f5;#2c3e50;#e67e22;#7f8c8d;#95a5a6;#bdc3c7;#9b59b6;#e0e0e0;#ecf0f1
