# Scheme name: Gruvbox Material Light, Hard
# Scheme author: Mayush Kumar (https://github.com/MayushKumar), sainnhe (https://github.com/sainnhe/gruvbox-material-vscode)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Gruvbox Material Light, Hard.16
ColorForeground=#654735
ColorBackground=#f9f5d7
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#fbf1c7;#c14a4a;#6c782e;#b47109;#45707a;#e78a4e;#4c7a5d;#3c3836;#f9f5d7;#c35e0a;#e0cfa9;#a89984;#c9b99a;#945e80;#654735;#282828
