# Scheme name: Rosé Pine Dawn
# Scheme author: Emilia Dunfelt &lt;sayhi@dunfelt.se&gt;
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Rosé Pine Dawn
ColorForeground=#575279
ColorBackground=#faf4ed
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#faf4ed;#1f1d2e;#d7827e;#ea9d34;#56949f;#907aa9;#286983;#575279;#9893a5;#1f1d2e;#d7827e;#ea9d34;#56949f;#907aa9;#286983;#26233a
