# Scheme name: Dracula
# Scheme author: Mike Barkmin (http://github.com/mikebarkmin) based on Dracula Theme (http://github.com/dracula)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Dracula
ColorForeground=#e9e9f4
ColorBackground=#282936
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#282936;#ea51b2;#ebff87;#00f769;#62d6e8;#b45bcf;#a1efe4;#e9e9f4;#626483;#ea51b2;#ebff87;#00f769;#62d6e8;#b45bcf;#a1efe4;#f7f7fb
