# Scheme name: vice
# Scheme author: Thomas Leon Highbaugh thighbaugh@zoho.com
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-vice.16
ColorForeground=#8b9cbe
ColorBackground=#17191e
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#22262d;#ff29a8;#0badff;#f0ffaa;#00eaff;#ff3d81;#8265ff;#b2bfd9;#17191e;#85ffe0;#3c3f4c;#383a47;#555e70;#00f6d9;#8b9cbe;#f4f4f7
