# Scheme name: Heetch Dark
# Scheme author: Geoffrey Teale (tealeg@gmail.com)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Heetch Dark.16
ColorForeground=#bdb6c5
ColorBackground=#190134
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#392551;#27d9d5;#c33678;#8f6c97;#bd0152;#470546;#f80059;#dedae2;#190134;#5ba2b6;#5a496e;#7b6d8b;#9c92a8;#82034c;#bdb6c5;#feffff
