# Scheme name: Horizon Light
# Scheme author: Michaël Ball (http://github.com/michael-ball/)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Horizon Light
ColorForeground=#403c3d
ColorBackground=#fdf0ed
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#fdf0ed;#f7939b;#94e1b0;#fbe0d9;#da103f;#1d8991;#dc3318;#403c3d;#bdb3b1;#f7939b;#94e1b0;#fbe0d9;#da103f;#1d8991;#dc3318;#201c1d
