# Scheme name: Tokyo Night Moon
# Scheme author: Ólafur Bjarki Bogason
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Tokyo Night Moon
ColorForeground=#3b4261
ColorBackground=#222436
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#222436;#ff757f;#c3e88d;#ffc777;#82aaff;#fca7ea;#86e1fc;#3b4261;#636da6;#ff757f;#c3e88d;#ffc777;#82aaff;#fca7ea;#86e1fc;#c8d3f5
