# Scheme name: Tokyo City Terminal Dark
# Scheme author: Michaël Ball
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Tokyo City Terminal Dark
ColorForeground=#d8e2ec
ColorBackground=#171d23
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#171d23;#d95468;#8bd49c;#ebbf83;#539afc;#b62d65;#70e1e8;#d8e2ec;#526270;#d95468;#8bd49c;#ebbf83;#539afc;#b62d65;#70e1e8;#fbfbfd
