# Scheme name: Everforest Dark Hard
# Scheme author: Sainnhe Park (https://github.com/sainnhe)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Everforest Dark Hard.16
ColorForeground=#d3c6aa
ColorBackground=#272e33
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#2e383c;#e67e80;#a7c080;#dbbc7f;#7fbbb3;#9da9a0;#83c092;#edeada;#272e33;#e69875;#414b50;#859289;#9da9a0;#d699b6;#d3c6aa;#fffbef
