# Scheme name: Summerfruit Dark
# Scheme author: Christopher Corley (http://christop.club/)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Summerfruit Dark.16
ColorForeground=#d0d0d0
ColorBackground=#151515
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#202020;#ff0086;#00c918;#aba800;#3777e6;#cc6633;#1faaaa;#e0e0e0;#151515;#fd8900;#303030;#505050;#b0b0b0;#ad00a1;#d0d0d0;#ffffff
