# Scheme name: ShadeSmear Dark
# Scheme author: Kyle Giammarco (http://kyle.giammar.co)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-ShadeSmear Dark.16
ColorForeground=#dbdbdb
ColorBackground=#232323
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#1c1c1c;#cc5450;#71983b;#307878;#376388;#6d6d6d;#c57d42;#e4e4e4;#232323;#a64270;#4e4e4e;#c0c0c0;#e4e4e4;#d7ab54;#dbdbdb;#1c1c1c
