# Scheme name: Rosé Pine
# Scheme author: Emilia Dunfelt &lt;edun@dunfelt.se&gt;
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Rosé Pine.16
ColorForeground=#e0def4
ColorBackground=#191724
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#1f1d2e;#eb6f92;#31748f;#ebbcba;#c4a7e7;#524f67;#9ccfd8;#e0def4;#191724;#f6c177;#26233a;#6e6a86;#908caa;#f6c177;#e0def4;#524f67
