# Scheme name: Solarized Dark
# Scheme author: Ethan Schoonover (modified by aramisgithub)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Solarized Dark.16
ColorForeground=#93a1a1
ColorBackground=#002b36
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#073642;#dc322f;#859900;#b58900;#268bd2;#d33682;#2aa198;#eee8d5;#002b36;#cb4b16;#586e75;#657b83;#839496;#6c71c4;#93a1a1;#fdf6e3
