# Scheme name: Catppuccin
# Scheme author: Pocco81 (https://github.com/pocco81)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Catppuccin.16
ColorForeground=#d7dae0
ColorBackground=#1e1e28
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#1a1826;#f28fad;#abe9b3;#fae3b0;#96cdfb;#f2cdcd;#b5e8e0;#f5e0dc;#1e1e28;#f8bd96;#302d41;#575268;#6e6c7c;#ddb6f2;#d7dae0;#c9cbff
