# Scheme name: Cupcake
# Scheme author: Chris Kempson (http://chriskempson.com)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Cupcake.16
ColorForeground=#8b8198
ColorBackground=#fbf1f2
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#f2f1f4;#d57e85;#a3b367;#dcb16c;#7297b9;#baa58c;#69a9a7;#72677e;#fbf1f2;#ebb790;#d8d5dd;#bfb9c6;#a59daf;#bb99b4;#8b8198;#585062
