# Scheme name: Silk Light
# Scheme author: Gabriel Fontes (https://github.com/Misterio77)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Silk Light.16
ColorForeground=#385156
ColorBackground=#e9f1ef
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#ccd4d3;#cf432e;#6ca38c;#cfad25;#39aac9;#865369;#329ca2;#0e3c46;#e9f1ef;#d27f46;#90b7b6;#5c787b;#4b5b5f;#6e6582;#385156;#d2faff
