# Scheme name: Eva Dim
# Scheme author: kjakapat (https://github.com/kjakapat)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Eva Dim.16
ColorForeground=#9fa2a6
ColorBackground=#2a3b4d
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#3d566f;#c4676c;#5de561;#cfd05d;#1ae1dc;#bb64a9;#4b8f77;#d6d7d9;#2a3b4d;#ff9966;#4b6988;#55799c;#7e90a3;#9c6cd3;#9fa2a6;#ffffff
