# Scheme name: Deep Oceanic Next
# Scheme author: spearkkk (https://github.com/spearkkk/deep-oceanic-next)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Deep Oceanic Next.16
ColorForeground=#dce3e8
ColorBackground=#003b46
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#004f5e;#e6454b;#85b57a;#ffcc66;#3a82e6;#e673a3;#4da6a6;#e6ebf0;#003b46;#ff6a4b;#006374;#007a8a;#0093a3;#8c4de6;#dce3e8;#f0f5f5
