# Scheme name: tender
# Scheme author: Jacobo Tabernero (https://github/com/jacoborus/tender.vim)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-tender.16
ColorForeground=#eeeeee
ColorBackground=#282828
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#383838;#f43753;#c9d05c;#ffc24b;#b3deef;#a16946;#73cef4;#e8e8e8;#282828;#dc9656;#484848;#4c4c4c;#b8b8b8;#d3b987;#eeeeee;#feffff
