# Scheme name: Horizon Terminal Dark
# Scheme author: Michaël Ball (http://github.com/michael-ball/)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Horizon Terminal Dark.16
ColorForeground=#cbced0
ColorBackground=#1c1e26
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#232530;#e95678;#29d398;#fac29a;#26bbd9;#f09383;#59e1e3;#dcdfe4;#1c1e26;#fab795;#2e303e;#6f6f70;#9da0a2;#ee64ac;#cbced0;#e3e6ee
