# Scheme name: ShadeSmear Light
# Scheme author: Kyle Giammarco (http://kyle.giammar.co)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-ShadeSmear Light.16
ColorForeground=#232323
ColorBackground=#dbdbdb
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#e4e4e4;#cc5450;#71983b;#307878;#376388;#6d6d6d;#c57d42;#1c1c1c;#dbdbdb;#a64270;#c0c0c0;#4e4e4e;#1c1c1c;#d7ab54;#232323;#e4e4e4
