# Scheme name: Windows 10 Light
# Scheme author: Fergus Collins (https://github.com/C-Fergus)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Windows 10 Light.16
ColorForeground=#767676
ColorBackground=#f2f2f2
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#e5e5e5;#c50f1f;#13a10e;#c19c00;#0037da;#16c60c;#3a96dd;#414141;#f2f2f2;#f9f1a5;#d9d9d9;#cccccc;#ababab;#881798;#767676;#0c0c0c
