# Scheme name: Gruvbox dark, hard
# Scheme author: Dawid Kurek (dawikur@gmail.com), morhetz (https://github.com/morhetz/gruvbox)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Gruvbox dark, hard.16
ColorForeground=#d5c4a1
ColorBackground=#1d2021
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#3c3836;#fb4934;#b8bb26;#fabd2f;#83a598;#d65d0e;#8ec07c;#ebdbb2;#1d2021;#fe8019;#504945;#665c54;#bdae93;#d3869b;#d5c4a1;#fbf1c7
