# Scheme name: Black Metal (Bathory)
# Scheme author: metalelf0 (https://github.com/metalelf0)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Black Metal (Bathory)
ColorForeground=#c1c1c1
ColorBackground=#000000
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#000000;#5f8787;#fbcb97;#e78a53;#888888;#999999;#aaaaaa;#c1c1c1;#333333;#5f8787;#fbcb97;#e78a53;#888888;#999999;#aaaaaa;#c1c1c1
