# Scheme name: Ayu Light
# Scheme author: Khue Nguyen &lt;Z5483Y@gmail.com&gt;
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Ayu Light.16
ColorForeground=#5c6773
ColorBackground=#fafafa
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#f3f4f5;#f07178;#86b300;#f2ae49;#36a3d9;#e6ba7e;#4cbf99;#242936;#fafafa;#fa8d3e;#f8f9fa;#abb0b6;#828c99;#a37acc;#5c6773;#1a1f29
