# Scheme name: Flat
# Scheme author: Chris Kempson (http://chriskempson.com)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-flat
ColorForeground=#e0e0e0
ColorBackground=#2c3e50
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#2c3e50;#e74c3c;#2ecc71;#f1c40f;#3498db;#9b59b6;#1abc9c;#e0e0e0;#7f8c8d;#e74c3c;#2ecc71;#f1c40f;#3498db;#9b59b6;#1abc9c;#ecf0f1
