# Scheme name: Sandcastle
# Scheme author: George Essig (https://github.com/gessig)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Sandcastle.16
ColorForeground=#a89984
ColorBackground=#282c34
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#2c323b;#83a598;#528b8b;#a07e3b;#83a598;#a87322;#83a598;#d5c4a1;#282c34;#a07e3b;#3e4451;#665c54;#928374;#d75f5f;#a89984;#fdf4c1
