# Scheme name: Oxocarbon Light
# Scheme author: shaunsingh/IBM
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Oxocarbon Light.16
ColorForeground=#393939
ColorBackground=#f2f4f8
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#dde1e6;#ff7eb6;#0f62fe;#ff6f00;#42be65;#37474f;#673ab7;#525252;#f2f4f8;#ee5396;#525252;#161616;#262626;#be95ff;#393939;#08bdba
