# Scheme name: Pasque
# Scheme author: Gabriel Fontes (https://github.com/Misterio77)
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-xfce-terminal)
[Scheme]
Name=base16-pasque
ColorForeground=#dedcdf
ColorBackground=#271c3a
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#271c3a;#a92258;#c6914b;#804ead;#8e7dc6;#953b9d;#7263aa;#dedcdf;#3e2d5c;#a92258;#c6914b;#804ead;#8e7dc6;#953b9d;#7263aa;#bbaadd
