# Scheme name: Atelier Dune Light
# Scheme author: Bram de Haan (http://atelierbramdehaan.nl)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Atelier Dune Light.16
ColorForeground=#6e6b5e
ColorBackground=#fefbec
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#e8e4cf;#d73737;#60ac39;#ae9513;#6684e1;#d43552;#1fad83;#292824;#fefbec;#b65611;#a6a28c;#999580;#7d7a68;#b854d4;#6e6b5e;#20201d
