# Scheme name: Atelier Heath
# Scheme author: Bram de Haan (http://atelierbramdehaan.nl)
# Template author: Tinted Theming (https://github.com/tinted-theming)
[Scheme]
Name=Base16-Atelier Heath.16
ColorForeground=#ab9bab
ColorBackground=#1b181b
ColorCursor=x
ColorBoldIsBright=FALSE
ColorPalette=#292329;#ca402b;#918b3b;#bb8a35;#516aec;#cc33cc;#159393;#d8cad8;#1b181b;#a65926;#695d69;#776977;#9e8f9e;#7b59c0;#ab9bab;#f7f3f7
